### ISSUE TITLE
template.json and parameters.json issues

### ISSUE THREAD

**Issue by njsee** [kirkryan/anfScheduler#1]
Hi,
Thanks for making the logicApp for ANF Snapshots. It will be very helpful to allot of ANF customers.
I noticed 2 issues while deploying the template into my sub:

In the template.json file, it had values for principalId and tenantId, but type: systemAssigned.
This resulted in an error.
Setting these to null allowed the template to deploy.

                "principalId": null,
                "tenantId": null,
                "type": "SystemAssigned"

In parameters.json, it had a parameter of workflows_Scheduler_ANF_Snapshots_v1_name, but no value.
I updated to below and it worked fine.

     "parameters": {
        "workflows_Scheduler_ANF_Snapshots_v1_name": {
            "value": "Scheduler-ANF-Snapshots-v1",
	     "type": "String"
        }

**Comment by kirkryan** [comment]
Thanks for your contribution @njsee - I’ll fix these and bump the version.

**Comment by kirkryan** [comment]
Added recommended fixes in [3751d88]. Thanks @njsee 
 (https://github.com/kirkryan/anfScheduler/commit/3751d8873d9c707306aaff50e333f4962403a7c0)
