### ISSUE TITLE
Kudos - worked on the first try!

### ISSUE THREAD

**Issue by MaxMelcher** [kirkryan/anfScheduler#2]
Hey Kirk, 

thanks for the logic app, it worked on the first try! 
We used azure cloud shell to deploy, I think that would be worth to document.

One tiny question: What is the firstSnapshot variable? 

Thanks a lot,
Max

**Comment by kirkryan** [comment]
Hey Max! Glad you enjoyed it! That's used to track internal logic - where it locates the most recent snapshot and then implements your retention logic against it. Good shout as there are different PowerShell versions of Az in the cloud shell - I think I had a separate PS script just for cloud shell actually.
