### ISSUE TITLE
Unable to find resource when running

### ISSUE THREAD

**Issue by ghost** [kirkryan/anfScheduler#4]
Below is the error I am getting when trying to run the script.  I know that the ANF Account, capacity pool and volume as well as the resource group are right. Is it possible that the script itself is putting together the URI wrong?  

{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.NetApp/netAppAccounts/cef63280-8db1-451c-90fa-02f94a2989bb/capacityPools/ANFFSPool1/volumes/OSNShares1' under resource group 'NerdioRG' was not found."
  }
}

**Comment by ghost** [comment]
I figured out the issue with this and another one:

1. In the code used to deploy it the location is specified as westerneurope and no matter what you specify in the deployment template blanks it deploys to westerneurope unless you manually change the code to the desired location.

2. Once deployed I encountered the issue I mentioned above and found that the ANFAccount parameter in the app was showing the subscription id and not the actual anfaccount value I had put in during the deployment setup.  Once I changed it from the subscription id to the anfaccount name the logic app worked great.  

So those 2 things need a touch up but thanks a lot for the app and it will go great with our several ANF capacity pools and volumes to help us keep snapshots protecting the data.

**Comment by kirkryan** [comment]
This is now fixed and a location field has been added.

**Comment by kirkryan** [comment]
@jasonwhand  - Thanks for taking the time to report the issue.
