### ISSUE TITLE
Line 24 of the template needs a comma

### ISSUE THREAD

**Issue by cjpalmer** [kirkryan/anfScheduler#6]
When trying to install the template, it fails with the following error:

There was an error loading the template from... (see screenshot)

Upon review of the template, there is a comma missing on line 24.
![LogicAppError](https://user-images.githubusercontent.com/12123472/84394719-53bfa200-abcb-11ea-8008-05b89caf64f6.jpg)

**Comment by kirkryan** [comment]
Thanks, this is now fixed.
