### ISSUE TITLE
Error when deploying the template

### ISSUE THREAD

**Issue by haanc** [kirkryan/anfScheduler#7]
There is a comma missing in the template. I've added the comma, but deployment still failed
Cannot deploy the template. The error message is showing below.
<img width="1919" alt="Error 1" src="https://user-images.githubusercontent.com/66817296/84471432-e89fc980-acb7-11ea-802b-500727ef47cb.PNG">
<img width="371" alt="Error 1 1" src="https://user-images.githubusercontent.com/66817296/84471436-ea698d00-acb7-11ea-86f0-732fab27dcb7.PNG">
<img width="398" alt="Error 1 2" src="https://user-images.githubusercontent.com/66817296/84471441-eb022380-acb7-11ea-86af-2ce5d1edaca0.PNG">

**Comment by kirkryan** [comment]
Thanks, this is now fixed.
