### ISSUE TITLE
Not deleting the old snapshots as per retention.

### ISSUE THREAD

**Issue by alishavez7** [kirkryan/anfScheduler#8]
Hi Kirk,

I have implemented the Logic apps workflow to schedule the ANF volume snapshot. It's taking the snapshot of all the volumes in that capacity pool without any issue.

I reduced the interval/frequency as 2/Hours and retention as 2, now it should keep the 2 latest snapshot but it's deleting the old snapshot for first Volume and rest of all Volumes keeping all the snapshots.

I checked the ANF activity logs and found that the delete command is running number of times to delete the old snapshot but every time it's picking the same snapshot id from first Volume.

i changed the snapshot prefix name, hope it wont create the issues.

Means delete function is not working correctly, did you face such issue in past? any help or suggestion would be greatly appreciated.

Thanks,
Shavez Ali

**Comment by kirkryan** [comment]
I am actively replicating this issue in my lab and can see the logic that is causing this behaviour. I hope to have a fix today.

**Comment by kirkryan** [comment]
This is now fixed in the latest version pushed a today. Thanks, @alishavez7

**Comment by alishavez7** [comment]
Hi Kirk,

Thanks for your help. Now ANF scheduler is working as expected.

Thanks,
Shavez Ali
